CREATE TABLE containers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    identifier_name TEXT NOT NULL,
    shipment_type TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE packages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tracking_id VARCHAR(255) NOT NULL UNIQUE,
    pseudoname VARCHAR(255) NOT NULL,
    weight FLOAT NOT NULL,
    volumetric_measure FLOAT NOT NULL,
    contact_number BIGINT NOT NULL,
    container_id INT,
    FOREIGN KEY (container_id) REFERENCES containers(id) ON DELETE SET NULL
);

CREATE TABLE statuses (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    package_id INT NOT NULL,
    status VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE CASCADE
);
